#!/bin/sh

#if ! pgrep -x "conky" >/dev/null; then
#    prime-run conky -c \
#        ~/.config/conky/SiriusF/Sirius.conf >/dev/null &
#    prime-run conky -c \
#        ~/.config/conky/SiriusF/Sirius2.conf >/dev/null &
#else
#    killall conky
#    prime-run conky -c \
#        ~/.config/conky/SiriusF/Sirius.conf >/dev/null &
#    prime-run conky -c \
#        ~/.config/conky/SiriusF/Sirius2.conf >/dev/null &
#fi

#if ! pgrep -x "glava" > /dev/null; then
#    prime-run glava > /dev/null &
#else
#    killall glava
#    prime-run glava > /dev/null &
#fi
xrdb ~/.Xresources
xrdb -merge ~/.cache/hellwal/colors.Xresources

killall -q polybar
polybar bar 2>&1 | tee -a /tmp/polybar1.log &
disown
