# keymap.toml
[[mgr.prepend_keymap]]
on   = "="
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

[[manager.prepend_keymap]]
on   = ["R"]
run  = "plugin rotate-image"
desc = "Rotate images"

[[manager.prepend_keymap]]
on   = [ "c", "p" ]
run  = "plugin command"
desc = "Yazi command prompt"
