#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
source $HOME/.cache/hellwal/colors-bsp
source $HOME/.config/bspwm/sc/resize-gaps compress

bspc monitor -d 1 2 3 4

# Appearance
bspc config border_width 20
#source $HOME/.config/bspwm/sc/borders
#bspc config border_radius 20
#bspc config normal_border_color "#000000"
#bspc config focused_border_color "#000000"

bspc config split_ratio 0.50
bspc config borderless_monocle false

# Behaviour
bspc config focus_follows_pointer true
bspc config history_aware_focus false
bspc config focus_by_distance true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a XAVA border=off

# Tweaks

xsetroot -cursor_name left_ptr

source $HOME/.config/bspwm/sc/autostart
source $HOME/.config/bspwm/sc/2b
